---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rhcdn-proxy
  name: rhcdn-proxy
  namespace: rhcdn-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhcdn-proxy
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rhcdn-proxy
    spec:
      containers:
      - image: ghcr.io/karelvanhecke/rhcdn-proxy:v0.2.4@sha256:b4937b6b0a3d08686597e3796cf2078d81dc31538a0f10d2c5e7204f8c2533d3
        name: rhcdn-proxy
        env:
        - name: org
          valueFrom:
            secretKeyRef:
              name: rhcdn-proxy
              key: org
        - name: activationkey
          valueFrom:
            secretKeyRef:
              name: rhcdn-proxy
              key: activationkey
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /cache
          name: rhcdn-proxy
      volumes:
      - name: rhcdn-proxy
        emptyDir:
          sizeLimit: 20Gi
