name: Build
on:
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=ref,event=pr

      - name: Build image
        id: build
        uses: docker/build-push-action@v4
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,oci-mediatypes=true

      - name: Scan image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          ignore-unfixed: true
          exit-code: 1
