name: Release
on:
  push:
    tags:
      - v*.*.*

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release-image:
    name: Release image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAME }}
            quay.io/${{ env.IMAGE_NAME }}
          tags: type=semver,pattern={{raw}}

      - name: Build and push image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=registry,oci-mediatypes=true

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.2

      - name: Sign images
        run: |
          cosign sign --yes ghcr.io/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}
          cosign sign --yes quay.io/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}
