name: Release
on:
  push:
    tags:
      - v*.*.*

jobs:
  container-release:
    name: Build and release container
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build container
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: rhcdn-proxy
          tags: ${{ github.ref_name }} latest
          layers: true
          oci: true
          containerfiles: |
            ./Containerfile

      - name: Push container to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/karelvanhecke
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Push container to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/karelvanhecke
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
