name: Release manifests
on:
  push:
    tags:
    - manifests-v*.*.*

env:
  IMAGE_NAME: ${{ github.repository_owner }}/manifests/rhcdn-proxy
  REGISTRY: ghcr.io

jobs:
  release-manifests:
    name: Release manifests
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Flux CLI
      uses: fluxcd/flux2/action@main

    - name: Push manifests to registries
      id: flux-push-artifact
      run: >
        flux push artifact oci://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_REF_NAME##manifests-}
        --path ./deploy
        --revision ${{ github.ref_name }}@sha1:${{ github.sha }}
        --source ${{ github.server_url }}/${{ github.repository }}
        --output json |
        jq -r .digest |
        echo "digest=$(</dev/stdin)" >> $GITHUB_OUTPUT

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.2.0

    - name: Sign manifests
      run: |
        cosign sign --yes ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.flux-push-artifact.outputs.digest }}
